netbeans.apache.org/src/content/community/events.asciidoc

Moving content from https://cwiki.apache.org/confluence/display/NETBEANS/NetBeans+Events to netbeans.apache.org, next step is to add list of upcoming events, locations, etc.

Updated content for Apache NetBeans Events

---

netbeans.apache.org/src/content/download/nb90/nb90-beta.asciidoc

The "dev" space should only be used for staging releases for voting, not for general users. Moreover, "dist/dev/incubator/netbeans/incubating-netbeans-java/incubating-9.0-beta" is actually RC1, which was never released.

Download PGP signature and MD5 and SHA1 sums from a correct locations.

---

netbeans.apache.org/src/content/community/who.asciidoc

Updating the who is who page, marking John as a committer (& testing jenkins job)

Update who.asciidoc - John as committer

---

netbeans.apache.org/src/content/help/index.asciidoc

It should be an absolute path. See https://netbeans.apache.org/help/index.html which sends you to the non-existing https://netbeans.apache.org/help/wiki/index.asciidoc

Fixes the first link to the wiki index

---

netbeans.apache.org/src/content/templates/footer.gsp

It seems the whimsy website tool at https://whimsy.apache.org/pods/project/netbeans requires _BOTH_ a link with text "license" and href "^https?://.*apache.org/licenses/$", let's do that.

[NETBEANS-636] license link for whimsy

---

netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/download/nb90/index.asciidoc
netbeans.apache.org/src/content/download/nb90/nb90.asciidoc
netbeans.apache.org/src/content/templates/footer.gsp
netbeans.apache.org/src/content/templates/news.gsp
netbeans.apache.org/src/content/templates/slider.gsp

In preparation for the 9.0 Release. 
Still missing:
- Links to votes.
- Verify links to final artifacts.
- Setting the final release date.

NetBeans 9.0 Release Announcement

---

netbeans.apache.org/src/content/community/who.asciidoc

I haven't been active for over one year in NB and have no time nor plans to do so

Remove markiewb from "who is who" page

---

netbeans.apache.org/gradle/deps.gradle

Fixing the version of jbake-gradle-plugin, otherwise we get a
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `start_with?' for nil:NilClass
at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:341)
at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:448)
at org.jbake.parser.AsciidoctorEngine.processAsciiDoc(AsciidoctorEngine.java:141)
`

Hotfix: jbake fails with undefined method start_with?

---

netbeans.apache.org/src/content/community/mailing-lists.asciidoc

This PR just fixes a typo in the Mailing Lists page.

Fix "ununsubscribe" typo in mailing list page

---

bits.netbeans.org/README.asciidoc
netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/participate/submit-pr.asciidoc

Currently, the name "GitHub" is styled as both "GitHub" and "github" in this web site. This PR changes it to be "GitHub" everywhere, for internal consistency, and to match the styling that GitHub itself uses.

Style "GitHub" with capitalization

---

netbeans.apache.org/src/content/scss/common/_netbeans.scss

Some SCSS improvements:
- Tables are no longer width:100%.
- We hide sect2 and up for TOC in mobile.
- Improved padding of main content.
These make the tutorials to look better (see for instance http://netbeans.apache.org/kb/docs/ide/git.html)

SCSS improvements for tutorials

---

netbeans.apache.org/src/content/templates/footer.gsp

Let's make it clear that Apache NetBeans and NetBeans are now trademarks of the Apache Software Foundation.

NetBeans Trademark Statement

---

netbeans.apache.org/src/content/kb/docs/java/code-inspect.asciidoc
netbeans.apache.org/src/content/kb/docs/java/debug-multithreaded.asciidoc
netbeans.apache.org/src/content/kb/docs/java/debug-visual.asciidoc
netbeans.apache.org/src/content/kb/docs/java/editor-codereference.asciidoc
netbeans.apache.org/src/content/kb/docs/java/editor-inspect-transform.asciidoc
netbeans.apache.org/src/content/kb/docs/java/groovy-quickstart.asciidoc
netbeans.apache.org/src/content/kb/docs/java/index.asciidoc
netbeans.apache.org/src/content/kb/docs/java/javase-deploy.asciidoc
netbeans.apache.org/src/content/kb/docs/java/javase-embedded.asciidoc
netbeans.apache.org/src/content/kb/docs/java/javase-intro.asciidoc
netbeans.apache.org/src/content/kb/docs/java/junit-intro.asciidoc
netbeans.apache.org/src/content/kb/docs/java/maven-hib-java-se.asciidoc
netbeans.apache.org/src/content/kb/docs/java/profile-loadgenerator.asciidoc
netbeans.apache.org/src/content/kb/docs/java/profiler-intro.asciidoc
netbeans.apache.org/src/content/kb/docs/java/quickstart-gui-legend.asciidoc
netbeans.apache.org/src/content/kb/docs/java/quickstart-gui.asciidoc
netbeans.apache.org/src/content/kb/docs/java/quickstart.asciidoc
netbeans.apache.org/src/content/templates/tutorial.gsp

Now tutorials use asciidoc level0.
This makes it easier to create ePub books, but requires reviewing some tutorials.
Examples of use:
/kb/docs/java/index.asciidoc
/kb/docs/java/quickstart.asciidoc
Basically:
- One level 0 header at the top of the document "= Whatever the title"
- The rest of headers start at level 1 "== " or greater.

Tutorials use level 0 header

---

netbeans.apache.org/build.gradle
netbeans.apache.org/src/content/community/committer.asciidoc
netbeans.apache.org/src/content/community/events.asciidoc
netbeans.apache.org/src/content/community/index.asciidoc
netbeans.apache.org/src/content/community/mailing-lists.asciidoc
netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/download/nb100/index.asciidoc
netbeans.apache.org/src/content/download/nb100/nb100.asciidoc
netbeans.apache.org/src/content/download/nb90/index.asciidoc
netbeans.apache.org/src/content/download/nb90/nb90.asciidoc
netbeans.apache.org/src/content/help/index.asciidoc
netbeans.apache.org/src/content/participate/index.asciidoc
netbeans.apache.org/src/content/participate/netcat.asciidoc
netbeans.apache.org/src/content/participate/report-issue.asciidoc
netbeans.apache.org/src/content/participate/submit-pr.asciidoc
netbeans.apache.org/src/content/plugins/index.asciidoc
netbeans.apache.org/src/content/scss/base/_colors.scss
netbeans.apache.org/src/content/scss/base/_fonts.scss
netbeans.apache.org/src/content/scss/base/_settings.scss
netbeans.apache.org/src/content/scss/common/_netbeans.scss
netbeans.apache.org/src/content/templates/head.gsp
netbeans.apache.org/src/content/templates/page.gsp
netbeans.apache.org/src/content/templates/wiki.gsp

- Links are magenta now (using same colors as in the logo), to differentiate them from headers.
- Using "Level 0" title as the title in the page (same as in tutorials).
- Redesigned some pages.
- More clear distinction between the download page and the features page.
- Changed fonts to "Open Sans".
NOTE: Please Squash & Merge.

Link colors / Header Sizes / Page Titles

---

netbeans.apache.org/src/content/scss/common/_netbeans.scss

Removes the black mobile title bar that shows up for a split second when loading the page on medium display sizes. Look at [this video at the given timestamp](https://youtu.be/0ovc902VWMQ?t=153) to see the error. The same problem occurs on small display sizes with the top bar (also fixed with this PR).

Fix responsive menu flashing

---

netbeans.apache.org/src/content/scss/common/_netbeans.scss

Reduce the amount the carousel / slider pushes down the landing page content when JavaScript is first executed.

Reduce carousel pop in on landing page

---

netbeans.apache.org/src/content/templates/slider.gsp

The carousel controls overlap the slide content on mobile devices. Swiping left / right works, so they are redundant anyway.

Remove overlapping carousel controls on mobile devices

---

netbeans.apache.org/src/content/kb/docs/java/editor-codereference.asciidoc

Turned on the :experimental: feature Asciidoctor to allow key combinations to appear as graphics.
Fixed table widths causing whitespace issues with the table of contents. Was set to a width of 75%, which is now removed on all tables.

Fixed table widths, added keyboard graphics

---

netbeans.apache.org/src/content/participate/submit-pr.asciidoc

This just fixes a typo in the "Submitting PRs" page.
This is a rebased version of #86.

Fix "boostraping" typo

---

netbeans.apache.org/build.gradle
netbeans.apache.org/src/content/download/maven/index.asciidoc
netbeans.apache.org/src/content/download/maven/index.cgi

Hi, this is a PR intended to put a cgi file that reintepret associated html page to allow mirror selection for download like in this page for Apache Maven 3.6.0
http://maven.apache.org/download.cgi?Preferred=http%3A%2F%2Fwwwftp.ciril.fr%2Fpub%2Fapache%2F
The resulting page will be there but I guess some configuration needs to be set with INFRA
https://netbeans.apache.org/download/maven/index.html
Regards

Creating download page for maven artefacts sources

---

netbeans.apache.org/src/content/.htaccess

I hope the folder for redirect is good. 
http://netbeans.apache.org/download/maven/index.html should be redirected to redirectedhttp://netbeans.apache.org/download/maven/index.cgi

Update htaccess for cgi script

---

netbeans.apache.org/src/content/participate/report-issue.asciidoc

Sometimes information is missing from issue reporters. So I think that we should add the note to the "Reporting issues" page.

Add the note to report-issue.asciidoc

---

netbeans.apache.org/src/content/.htaccess

This should redirect all not found pages to legacy netbeans.org. Let's see if this works.

htaccess redirect to legacy netbeans.org

---

netbeans.apache.org/src/content/download/nb110/index.asciidoc

I looked for a JIRA issue about Java EE 8 support but I couldn't find one so I'm linking to @juneau001 's post on the mailing list. On Java Off Heap I heard him say he's working on Java EE 8 support. Thanks!!

link to mailing list thread about Java EE 8 support

---

netbeans.apache.org/src/content/plugins/index.asciidoc

Update to mention only Apache Netbeans, as plugins are not limited to 9.0 Beta, or any other specific version - unless the plugin itself mentions it, which then would be outside the scope of the information on this page in particular.
Might be better than to say Netbeans 9.0+, as any version under the Apache name already implies such.

Generic Netbeans version

---

netbeans.apache.org/build.gradle
netbeans.apache.org/src/content/community/committer.asciidoc
netbeans.apache.org/src/content/community/mailing-lists.asciidoc
netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/help/index.asciidoc
netbeans.apache.org/src/content/kb/docs/contributing.asciidoc
netbeans.apache.org/src/content/kb/docs/ide/git.asciidoc
netbeans.apache.org/src/content/participate/netcat.asciidoc
netbeans.apache.org/src/content/participate/submit-pr.asciidoc
netbeans.apache.org/src/content/templates/footer.gsp
netbeans.apache.org/src/content/templates/tools.gsp
netbeans.apache.org/src/content/templates/tutorial.gsp

This updates the links for the post-incubation era.
Also adds the *.css at / for a future netbeans.org migration.

Updating post-incubation links

---

netbeans.apache.org/src/content/community/events.asciidoc

I have added CodeOne 2019 NetBeans links, DawsCon and NetBeans UK2019. I have also removed old 2018 entries but added some write-ups to previous events

Remove past events and add dates for 2019

---

netbeans.apache.org/src/content/kb/docs/java/javase-intro.asciidoc

"Java" category no longer exists as ant projects are no longer the default option in Netbeans.
This tutorial works with ant projects and the current category name for them is "Java with Ant".

Update the category name for ant projects

---

netbeans.apache.org/globals.yml
netbeans.apache.org/src/content/download/archive/index.asciidoc
netbeans.apache.org/src/content/download/dev/index.asciidoc
netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/download/nb111/index.asciidoc
netbeans.apache.org/src/content/download/nb111/nb111.asciidoc
netbeans.apache.org/src/content/index.asciidoc
netbeans.apache.org/src/content/templates/menu.gsp
netbeans.apache.org/src/content/templates/news.gsp
netbeans.apache.org/src/content/templates/page-front.gsp
netbeans.apache.org/src/content/templates/slider.gsp

Additional structural and content changes for Apache NetBeans 11.1 release.
- Fleshed out NB 11.1 download page with links
- Changed main menu download link to /download
- Simplified main download page and added text from mailing list thread.
- Added archive and dev sections, and moved content from /download page on to respective index pages.
- added new front page template copied from existing but put news back for now or we have no reference to the release (something to review further)
- reverted page-noaside for other page use (NB 11.1 info and download)
I used official Apache release date (today), but we could change to announcement date if you want?
References to installers, Snap, etc. need adding in after merging this.
As an aside, can we make sure links are full paths but without …

Website structural updates for NB 11.1.

---

netbeans.apache.org/src/content/download/nb111/index.asciidoc

PHP 7.4 is not supported completely in NB11.1. 
We should fix this because there is incorrect information in https://www.infoq.com/news/2019/07/netbeans-11-apache/ .
cc: @tmysik

Fix the information about PHP 7.4

---

netbeans.apache.org/src/content/download/dev/index.asciidoc

Mention JDK 11 with regards to building Netbeans, mention also the flag that needs to be enabled when using ant to build.
Have not tried to build with other, non-LTS, JDK, but if I can, will update this modification to reflect it.

Update notes on versions of JDK to build with

---

netbeans.apache.org/src/content/community/index.asciidoc

Move links to the actionable parts of sentences, e.g. "See ...".
Minor typo cleanup.

Move links, fix typo

---

netbeans.apache.org/src/content/help/commercial-support.asciidoc

Please remove my email from the Commercial Support page.
It seems that instead of being a page about Commercial Support it's a page where Commercial entities come for priority free support.

Remove Emilian from Commercial Support page

---

netbeans.apache.org/src/content/download/dev/index.asciidoc

Add a brief note about the JAVA_HOME and ANT_HOME environment variables
to the build instructions on the Web site and the GitHub repository. See
the following message on the mailing list for details:
Re: Building NetBeans 11.1 from source fails with compile errors
https://mail-archives.apache.org/mod_mbox/netbeans-dev/201910.mbox/%3C26c1f141-b021-4473-059f-41ec0b5e3613%40status6.com%3E
Fixes #3209

[NETBEANS-3209] Add JAVA_HOME and ANT_HOME note

---

netbeans.apache.org/src/content/download/nb111/nb111.asciidoc

Add the snap package (https://snapcraft.io/netbeans) as an alternative
for Linux systems on the Apache NetBeans 11.1 download page.
Fixes #3208

[NETBEANS-3208] Add Snap package to download page

---

netbeans.apache.org/src/content/download/dev/index.asciidoc

Change the Ant instructions to specify use of `ant build` rather than default `ant`. People wanting a binary closer to what is distributed should use the zip bundle, not the contents of `nbbuild/netbeans`

Update Ant build source instructions to use zip

---

netbeans.apache.org/src/content/download/archive/index.asciidoc
netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/download/nb111/nb111.asciidoc
netbeans.apache.org/src/content/download/nb112/index.asciidoc
netbeans.apache.org/src/content/download/nb112/nb112.asciidoc
netbeans.apache.org/src/content/templates/news.gsp

- change news header to point at new release
- update installer links to use mirrors
- change release date to official release date
- update build instructions
- move 11.1 to release archive page and change download links to use archive.apache.org

Complete update of website for release 11.2

---

netbeans.apache.org/src/content/kb/docs/java/quickstart-gui.asciidoc

Formatting on the QuickStart: GUI page is broken. Here's a quick fix.

Fix markup that was breaking formatting for Quickstart: GUI page

---

netbeans.apache.org/src/content/index.asciidoc

This will provide better visibility for the NetCAT program and make it easier for participants to sign up.

Add link to NetCAT wiki page.

---

netbeans.apache.org/src/content/download/maven/index.asciidoc
netbeans.apache.org/src/content/download/nb110/nb110.asciidoc
netbeans.apache.org/src/content/download/nb112/nb112.asciidoc
netbeans.apache.org/src/content/download/nb113/nb113.asciidoc

direct link to KEYS, asc or sha512 should prefer downloads.apache.org (noticed on infra)
https://blogs.apache.org/infra/entry/more-secure-and-robust-downloads
the https://www.apache.org/dyn* url should be kept
Added apidoc 11.2 and 11.3

migrate to downloads.apache.org -  missing apidoc link

---

netbeans.apache.org/src/content/.htaccess

This fixes https://issues.apache.org/jira/browse/NETBEANSINFRA-185 to finally get rid of legacy Plugin Portal 2.0 which is hosted on Oracle infrastructure.

Changing location of Plugin Portal Update Center for NetBeans 12.0

---

netbeans.apache.org/src/content/kb/docs/java/code-inspect.asciidoc

I couldn't figure out the correct syntax to get the list items to be at level 2 to be indented under step 3 of "Running Single Inspections" so both are currently level 1 (solid bullet) so that they are obviously of the same level rather than one being empty and one filled. I use InDesign and FrameMaker normally and need to figure out Asciidoc . Sorry.

fixed step numbers and bullet appearance

---

netbeans.apache.org/src/content/.htaccess

I noticed, that the backends for updatecenter redirects for dev still point to 11.3. Given, that 12.0 is about to be released and from my perspective netbeans dev should pair with the newest plugins, I suggest to switch the update center urls over.

Move dev uc to 12.0

---

netbeans.apache.org/src/content/templates/menu.gsp

From https://netbeans-vm.apache.org/pluginportal/ to https://plugins.netbeans.apache.org/

Update to the new Plugin Portal URL

---

netbeans.apache.org/src/content/download/nb121/nb121.asciidoc

Apache NetBeans will not start on macOS Big Sur.
The issue is in the nbexec script.
`/usr/libexec/java_home` changed in Big Sur and fails to find the JDK when the `--failfast` parameter is used with the `+` sign in the `-v 1.8.0+` parameter. 
The easiest workaround is to manually set `netbeans_jdkhome` in `netbeans.conf`
https://stackoverflow.com/questions/tagged/netbeans+macos-big-sur
https://dev.to/pablohs1986/macos-users-java-problems-in-big-sur-help-7pa

Add workaround for Apache NetBeans failing to run on macOS Big Sur.

---

netbeans.apache.org/src/content/participate/submit-pr.asciidoc

This PR adds the instructions described in 
https://lists.apache.org/thread.html/r45e7c6847056ef8f170f6aa5b7b81fca1e5ef87dcf05883178554b94%40%3Cdev.netbeans.apache.org%3E
to the Contributing Code page.
This is intended to complement the existing tutorial videos.

Add a Developing NetBeans section

---

netbeans.apache.org/src/content/.htaccess

INFRA-21530 didn't work as expected.
Adding some useful redirections in .htaccess, for easier handling (no INFRA involvement).

INFRA-21530 Improvements

---

netbeans.apache.org/src/content/.htaccess

netbeans.org redirection in netbeans-vm1 is sending us a spurious "/".

[NETBEANS-5420] RedirectMatch fix?

---

netbeans.apache.org/src/content/index.asciidoc

"Filing issues" link changed from direct link to JIRA to "Reporting issues" page.
This leads visitor to page where he can get more info how to report issue.

Filing issues link changed to dedicated page

---

netbeans.apache.org/src/content/tutorials/nbm-nodesapi2.asciidoc

Fixes a bad closing code fence in a page in the Nodes tutorial.
Without this, the rendered page breaks like this:

Fix bad code fence in Asciidoc for Nodes tutorial

---

netbeans.apache.org/src/content/download/nb120/index.asciidoc
netbeans.apache.org/src/content/download/nb122/nb122.asciidoc
netbeans.apache.org/src/content/download/nb123/index.asciidoc
netbeans.apache.org/src/content/download/nb123/nb123.asciidoc

Fix Javadoc link. Change links to NB 12.2 ready for archiving. Remove references to LTS being annual / in 2021.

Some post-release changes for NB 12.3

---

netbeans.apache.org/src/content/participate/report-issue.asciidoc

Without this it wasn't displayed as a green button but as a text link with words "button success" visible on the website

fix "Open Jira" button style on the Reporting issues page

---

netbeans.apache.org/src/content/download/nb123/nb123.asciidoc

Adds a note to the 12.3 download page indicating that the Swift 5 runtime is needed to launch 12.3 on macOS versions prior to 10.14.4

[NETBEANS-5481] add note for Swift 5 runtime on macOS < 10.14.4

---

Jenkinsfile.groovy

Hi @vieiro, was missing the fact that asf.yaml has to be on the publish branch.
Hope this change make us reach the green lines

make asfyaml file available on publish branch

---

netbeans.apache.org/src/content/kb/docs/cnd/toolchain.asciidoc

Some of the tables, starting with "Tool collection definition tags" were defined as 3 columns while several of the lines had only 2 columns of data, leading to scrambled tables.
All I did was add a 3rd vertical bar on lines that didn't have them.  I have not evaluated the result for content, although at a glance it seems much more readable.

Include 3 columns in all 3 column tables

---

netbeans.apache.org/src/content/download/archive/index.asciidoc
netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/download/nb120/index.asciidoc

Added information on 12.0 being EOL'd in the near future, and that it doesn't support Java 15+. This was cause of a few issues on JIRA.
Also updated the archive page that was missing 12.4, and made the release titles simpler / consistent for our new post-LTS world! :smile:

Add 12.0 LTS EOL information and fix up archived releases.

---

netbeans.apache.org/src/content/community/mailing-lists.asciidoc
netbeans.apache.org/src/content/participate/report-issue.asciidoc
netbeans.apache.org/src/content/participate/submit-pr.asciidoc

Change references and links from JIRA to GitHub issues on a few key pages, in particular the Report Issues page.
The Report Issues page is currently the landing page from the `Help / Report Issue` action (and elsewhere) in the IDE. It is redirected from https://netbeans.apache.org/nb/report-issue in .htaccess.  We could decide to redirect straight to https://github.com/apache/netbeans/issues/new/choose ?  I can update this PR with that.

Update some key JIRA links to point to GitHub issues.

---

netbeans.apache.org/src/content/community/events.asciidoc

Removed Upcoming events paragraph as the events already happened. Also added link to a session from Dawscon 2021.

Remove Upcoming events paragraph as the events already happened

---

netbeans.apache.org/src/content/wiki/ProxyBasicAuth.asciidoc

We explain what happens with HTTP Basic Authentication for proxies with Oracle JDK > 8u111.

Explanation for issue #3748

---

netbeans.apache.org/src/content/download/nb13/nb13.asciidoc

Remove the note about building / running on JDK 8. This was intended purely for 12.6.

Remove note about building / running on JDK 8

---

netbeans.apache.org/src/content/download/nb13/nb13.asciidoc

Added a community installers section to download page, with important info on them not being official ASF binaries / possible additional terms, along with links to Codelerity / Gj IT installers.

Add community installers section to download page

---

netbeans.apache.org/src/content/kb/docs/cnd/c-unit-test.asciidoc

This update fixes the problem for the configure file since for the new CUnit release (2.1-3) the downloaded tearred package doesnt contain the configure file

Update to fix problem for ./configure: no such file or directory

---

netbeans.apache.org/src/content/dtds/README.txt
netbeans.apache.org/src/content/ns/ant-project-libraries/1.xsd
netbeans.apache.org/src/content/ns/j2se-project/1.xsd
netbeans.apache.org/src/content/ns/j2se-project/2.xsd

Hi the 3 missing xsd quoted from api doc.
Changed the link in the dtd folder for a valid one.

add xsd linked from apidoc

---

netbeans.apache.org/src/content/projects/autoupdate/nbm/nbm_package.asciidoc
netbeans.apache.org/src/content/projects/buildsys/build-sys-ui-spec.asciidoc
netbeans.apache.org/src/content/projects/buildsys/design.asciidoc
netbeans.apache.org/src/content/projects/buildsys/j2se-project-ui-spec.asciidoc
netbeans.apache.org/src/content/projects/lexer/index.asciidoc
netbeans.apache.org/src/content/projects/lexer/token-id-naming.asciidoc
netbeans.apache.org/src/content/projects/platform/articles/installation.asciidoc
netbeans.apache.org/src/content/projects/platform/core/windowsystem/changes.asciidoc
netbeans.apache.org/src/content/projects/platform/core/windowsystem/index.asciidoc
netbeans.apache.org/src/content/projects/platform/openide/proposals/actions/design.asciidoc
netbeans.apache.org/src/content/projects/platform/openide/proposals/actions/impl.asciidoc
netbeans.apache.org/src/content/projects/platform/openide/proposals/actions/index.asciidoc
netbeans.apache.org/src/content/projects/platform/openide/proposals/arch/cli.asciidoc
netbeans.apache.org/src/content/projects/platform/openide/tutorial/review/opinions_37386.asciidoc
netbeans.apache.org/src/content/projects/schema2beans/index.asciidoc
netbeans.apache.org/src/content/projects/translatedfiles/index.asciidoc
netbeans.apache.org/src/content/projects/ui/code_folding/cf_uispec.asciidoc
netbeans.apache.org/src/content/projects/ui/themes/themes.asciidoc
netbeans.apache.org/src/content/projects/ui/versioningspecification/index.asciidoc
netbeans.apache.org/src/content/projects/ui/ws/ws_spec.asciidoc

Hi this is a bit like #607
Page contains only a redirection to web.archive of the former site. So we can at least get the info instead of having a 404 from apidoc.
There is not a lot of pages. I try to reorganize in only one projects folder hope it make sense.

apidoc referenced specs (web archive)

---

netbeans.apache.org/src/content/templates/platform_tutorial.gsp
netbeans.apache.org/src/content/templates/tools.gsp
netbeans.apache.org/src/content/templates/tutorial.gsp

- Removed the (outdated) links to the issue tracker on the "requires review" templates since I don't think filing issues is useful at this state of the page. The "edit page" links should be preferred.
- updated link in footer
I haven't updated this page:
https://github.com/apache/netbeans-website/blob/master/netbeans.apache.org/src/content/nb/issues.html
since it looks like something which used to be embedded in netbeans and is no longer used (probably this: https://github.com/apache/netbeans/pull/3410) and can be potentially removed in future.

updated issue tracker links.

---

netbeans.apache.org/src/content/kb/docs/java/javase-intro.asciidoc

In the page 'Developing General Java Applications', line 277 that starts with 'In the Projects window...', has the sentence:
'...JUnit 4.x and click **Add Libray** repeat...'. 
The word **Library** is misspelled as **Libray**. This commit only changes this word.

Misspelling in the Developing General Java Applications' page. 

---

netbeans.apache.org/src/content/download/archive/index.adoc
netbeans.apache.org/src/content/download/nb15/index.adoc
netbeans.apache.org/src/content/download/nb16/index.adoc

I've added in the Linux DEB and RPM packages to the NB16 page, and updated a few other bits of text.  Replaced the macOS tip, which is fixed in the JDK as far as I know, with temporary info on Gradle and JDK 19.
Updated the NB15 page to use the archive links.  Also added an update and commented out lines on the NB16 page for when it is time to archive that.  Had to remind myself how Eric had set up the variables (which makes it much easier when you remember! :smile: )

Update NB16 page Linux info and prepare NB15 for archive

---

netbeans.apache.org/src/content/download/nb16/index.adoc

moved a few items around for improved readability and consistency.
* some inline sidenote has been moved down to `Deployment Platforms` as additional `tip`
* snap moved to community section
* mentioned that the zip is platform independent. This required to change the bullet list slightly otherwise it would have looked ugly.
* tips/warning annotations are now consistently below the main text block. Since one was below and the other above.
[link to github preview](https://github.com/apache/netbeans-website/blob/afc6f1984febde6c5d860deddd3b0aeb97e0786f/netbeans.apache.org/src/content/download/nb16/index.adoc)

small download page cleanup.

---

netbeans.apache.org/src/content/download/nb17/index.adoc

chatted with @lkishalmi about this and this warning isn't needed anymore since the upgrade to gradle 8.0-rc1 resolved the JDK compatibility issue.

nb17 dl page: removed resolved known issue.

---

netbeans.apache.org/src/content/blogs/geertjan/index.adoc
netbeans.apache.org/src/content/download/nb123/index.adoc
netbeans.apache.org/src/content/kb/docs/cnd/remotedev-tutorial.adoc
netbeans.apache.org/src/content/tutorials/nbm-maven-commandline.adoc
netbeans.apache.org/src/content/tutorials/nbm-projecttype.adoc
netbeans.apache.org/src/content/tutorials/nbm-quick-start.adoc
netbeans.apache.org/src/content/wiki/APITest.adoc
netbeans.apache.org/src/content/wiki/DevFaqActionContextSensitive.adoc
netbeans.apache.org/src/content_ja/kb/docs/ide/clearcase_ja.adoc
netbeans.apache.org/src/content_ja/kb/docs/ide/subversion_ja.adoc
netbeans.apache.org/src/content_pt_BR/kb/docs/ide/clearcase_pt_BR.adoc
netbeans.apache.org/src/content_pt_BR/kb/docs/ide/subversion_pt_BR.adoc
netbeans.apache.org/src/content_ru/kb/docs/ide/clearcase_ru.adoc
netbeans.apache.org/src/content_ru/kb/docs/ide/subversion_ru.adoc
netbeans.apache.org/src/content_zh_CN/kb/docs/ide/clearcase_zh_CN.adoc
netbeans.apache.org/src/content_zh_CN/kb/docs/ide/subversion_zh_CN.adoc

some block where misplaced and prefer clean build to get new issue triggering log
some id were not ok by construction.
It's pure technical, not semantic chek.
to get better file identification using asciidoctor **/*.adoc in src folder. (otherwise it say stdin )

asciidoctor build fixes

---

netbeans.apache.org/src/content/kb/docs/java/javase-intro.adoc

The current paragraph does not mention the following details of the Project Properties dialog:
1.  Libraries may be added to the module path or the class path. It seems the JUnit and Hamfest libraries should be added to the classpath.
2.  These libraries must also be added to the Run Test tab for the tests to be run successfully.

Add detail to section on creating JUnit Tests

---

netbeans.apache.org/src/content/kb/docs/java/code-inspect.adoc

Removed references to the SpotBugs plugin and JSR305 from the Static Code Analysis tutorial.

Removed references to the SpotBugs plugin and JSR305

---

.asf.yaml

This should enable the preview of the HTML/CSS/etc. content in the "antora" branch into 
https://netbeans-antora.staged.apache.org/ 
Let's see if this works.

Antora preview in staging mode

---

.asf.yaml

The .asf.yaml must be in the antora branch, ASF-infra explains. Let's do that

Rollback antora preview.
