apache/netbeans-website

netbeans.apache.org/build.gradle
netbeans.apache.org/globals.yml
netbeans.apache.org/settings.gradle
netbeans.apache.org/src/content/community/committer.asciidoc
netbeans.apache.org/src/content/community/events.asciidoc
netbeans.apache.org/src/content/community/index.asciidoc
netbeans.apache.org/src/content/community/mailing-lists.asciidoc
netbeans.apache.org/src/content/community/who.asciidoc
netbeans.apache.org/src/content/help/commercial-support.asciidoc
netbeans.apache.org/src/content/help/index.asciidoc
netbeans.apache.org/src/content/index.asciidoc
netbeans.apache.org/src/content/participate/index.asciidoc
netbeans.apache.org/src/content/participate/netcat.asciidoc
netbeans.apache.org/src/content/participate/report-issue.asciidoc
netbeans.apache.org/src/content/participate/submit-pr.asciidoc
netbeans.apache.org/src/content/plugins/index.asciidoc
netbeans.apache.org/src/content/scss/base/_base.scss
netbeans.apache.org/src/content/scss/base/_colors.scss
netbeans.apache.org/src/content/scss/base/_fonts.scss
netbeans.apache.org/src/content/scss/common/_netbeans.scss
netbeans.apache.org/src/content/scss/components/_card.scss
netbeans.apache.org/src/content/scss/components/_footer.scss
netbeans.apache.org/src/content/scss/netbeans.scss
netbeans.apache.org/src/content/templates/README.asciidoc
netbeans.apache.org/src/content/templates/footer.gsp
netbeans.apache.org/src/content/templates/menu.gsp
netbeans.apache.org/src/content/templates/slider.gsp
netbeans.apache.org/src/content/templates/tools.gsp

Added some licenses, cards & proper bottom edit links (when in master).

Added licenses and a simple card component for the main page.

---

netbeans.apache.org/src/content/scss/common/_netbeans.scss
netbeans.apache.org/src/content/templates/slider.gsp

Fix duplicate frontpage slide and revert slide background code because of display issue.

Quick fixes for slider issues

---

netbeans.apache.org/src/content/help/index.asciidoc

Fix typo at Apache NetBeans website url

---

netbeans.apache.org/src/content/nb/9.0/issues.html

Add issues.html for in IDE issue dialog

Add issues.html for in IDE issue dialog

---

netbeans.apache.org/globals.yml
netbeans.apache.org/src/content/nb/issues.html
netbeans.apache.org/src/content/templates/raw.gsp

Raw files being filtered out by JBake.
Move to `/nb/issues.html`

Change / fix IDE issue reporting page.

---

netbeans.apache.org/src/content/community/committer.asciidoc
netbeans.apache.org/src/content/community/mailing-lists.asciidoc
netbeans.apache.org/src/content/participate/submit-pr.asciidoc

Fixed a few typos and resolved a couple of broken links for the NetBeans website.

Broken links fixed and typos resolved

---

netbeans.apache.org/src/content/community/committer.asciidoc
netbeans.apache.org/src/content/templates/footer.gsp

Fixed a link and a duplicate word.

Minor fixes

---

netbeans.apache.org/src/content/download/nb90/index.asciidoc
netbeans.apache.org/src/content/download/nb90/nb90-rc1.asciidoc
netbeans.apache.org/src/content/templates/news.gsp
netbeans.apache.org/src/content/templates/slider.gsp

In preparation of the NetBeans 9.0 RC1 release.
Pending links to votes and double-check download links.

NetBeans 9.0 RC1

---

netbeans.apache.org/src/content/community/who.asciidoc

Removed resigned organization
Added Personal web link
Added full URLs of GitHub and LinkedIn profiles

Update Personal information

---

netbeans.apache.org/src/content/help/getting-started.asciidoc
netbeans.apache.org/src/content/help/index.asciidoc
netbeans.apache.org/src/content/scss/components/_video.scss
netbeans.apache.org/src/content/scss/netbeans.scss
netbeans.apache.org/src/content/templates/footer.gsp

Adding Geertjan's videos on how to get started with the Apache NetBeans Platform.

Geertjan videos on getting started with the Platform

---

netbeans.apache.org/src/content/participate/build-run-debug-tutorials.asciidoc
netbeans.apache.org/src/content/participate/submit-pr.asciidoc

A new page linked to from "Participate/Contribute Code" with Geertjan's tutorial videos

Add links to tutorial videos to Participate section

---

netbeans.apache.org/src/content/community/who.asciidoc

I've searched ids one by one in http://people.apache.org/committer-index.html .
- Deleted ids which don't exist.
- Added ids for some committers.

Fix apache ids

---

netbeans.apache.org/src/content/nb/issues_redirect.html

https://github.com/apache/incubator-netbeans/pull/549
For Help-Report Issue, we should invoke this new page.

add jira redirect page

---

netbeans.apache.org/src/content/community/mailing-lists.asciidoc

Update mailing-lists.asciidoc.

Add freenode #netbeans IRC channel to community/mailing-lists page.

---

netbeans.apache.org/src/content/community/events.asciidoc

Adding Ken's session at the ApacheCon 2018.

ApacheCon 2018 Event

---

netbeans.apache.org/src/content/templates/slider.gsp

Adding the award to the slider in main page.

Dukes Choice Award 2018

---

netbeans.apache.org/src/content/download/index.asciidoc

Adding links to pre-Apache downloads

Links to pre-Apache versions

---

netbeans.apache.org/src/content/kb/docs/java/index.asciidoc

Reverts apache/incubator-netbeans-website#107

Revert "General Java tutorials"

---

netbeans.apache.org/src/content/kb/docs/java/groovy-quickstart.asciidoc

- Removing feedback link.
- Updated list numbering.

[tutorials] Groovy tutorial updated

---

netbeans.apache.org/src/content/scss/common/_netbeans.scss
netbeans.apache.org/src/content/templates/tutorial.gsp

Borders around tutorial images. Red borders for clickable ones, blue for non clickable images.

[NETBEANS-1867] Borders around tutorial images

---

netbeans.apache.org/src/content/scss/common/_netbeans.scss
netbeans.apache.org/src/content/templates/news.gsp

Reducing the height of the news bar.

news bar height

---

netbeans.apache.org/src/content/index.asciidoc
netbeans.apache.org/src/content/scss/components/_card.scss

This adds some colors and links to the homepage cards.

Colorizing the home page

---

netbeans.apache.org/src/content/kb/docs/java/annotations-custom.asciidoc
netbeans.apache.org/src/content/kb/docs/java/annotations-lombok.asciidoc
netbeans.apache.org/src/content/kb/docs/java/annotations.asciidoc

annotations tutorial (english only)

[NETBEANS-1867] [NETBEANS-1912] Tutorials java/a

---

netbeans.apache.org/src/content/kb/docs/php/configure-php-environment-mac-os.asciidoc
netbeans.apache.org/src/content/kb/docs/php/configure-php-environment-ubuntu.asciidoc
netbeans.apache.org/src/content/kb/docs/php/configure-php-environment-windows.asciidoc
netbeans.apache.org/src/content/kb/docs/php/index.asciidoc
netbeans.apache.org/src/content/kb/docs/php/project-setup.asciidoc
netbeans.apache.org/src/content/kb/docs/php/quickstart.asciidoc

[NETBEANS-1867] Some PHP tutorials

---

netbeans.apache.org/src/content/kb/docs/java/quickstart.asciidoc

Updated NOTES admonitions to be "1 sentence per line" for a cleaner easier read. Using "+" following a sentence allows the concatenation.
Added :experimental: to allow keyboard graphics to replace keyboard text.
Changed keyboard key combinations so they now appear as keyboard graphics.

Updated NOTES, and keyboard graphics

---

netbeans.apache.org/src/content/kb/docs/java/javase-intro.asciidoc

Fixed tables from having a width of 75%, resulting in whitespace.
Added :experimental: attribute so keyboard graphics can be used.
Changed all keyboard key short cuts to be keyboard graphics.

Fixed tables, added keyboard graphics

---

netbeans.apache.org/src/content/kb/docs/contributing.asciidoc

Added how to enable keyboard shortcut graphics using the :experimental: attribute and the kbd:[] macro
Added an example of asciidoc code to use the kbd:[] macro to produce a nice visual keyboard combination.

Added keyboard shortcut usage

---

netbeans.apache.org/src/content/scss/base/_settings.scss
netbeans.apache.org/src/content/scss/common/_netbeans.scss

Let's add some color to those keys. Let's make the size of the code sections a little bit bigger.

pre/code size, kbd styling

---

netbeans.apache.org/src/content/kb/docs/java/code-inspect.asciidoc

Fixed numbered lists.
Updated keyboard short cuts from text to graphics.
Fixed page anchoring. (were broken)
Fixed table images - missing "a" attribute outside of row.

Updated numbering, shortcuts, anchor, table images

---

netbeans.apache.org/src/content/scss/common/_netbeans.scss

This adjusts the keyboard short cut graphics only.
**CURRENTLY LOOKS LIKE THIS **
**PROPOSED NEW LOOK LIKE THIS **

Updated kbd styling to be cleaner

---

netbeans.apache.org/src/content/kb/docs/java/editor-inspect-transform.asciidoc

Corrected step numbering and formatting.
Added :experimental: attribute for keyboard graphics

Updated numbering and formatting

---

netbeans.apache.org/src/content/.htaccess

It seems .htaccess was redirecting the catalog file incorrectly.
See https://issues.apache.org/jira/browse/NETBEANS-2380

[NETBEANS-2380] Restoring .htaccess

---

netbeans.apache.org/src/content/community/committer.asciidoc

I cargo-culted this in Zipkin and @justinmclean noted there was an ordering bug.

Flip order of the process

---

netbeans.apache.org/src/content/templates/menu.gsp

Removing '(incubating)' from front page.

Removing '(incubating)' from front page.

---

netbeans.apache.org/src/content/download/nb100/nb100.asciidoc

Updating links of NetBeans 10.0 to point to the Apache archive.

Archiving NB 10.0

---

netbeans.apache.org/src/content/download/nb110/index.asciidoc

Should this verbiage be 'also' instead of 'algo'?

Change 'algo' to 'also'

---

netbeans.apache.org/src/content/.htaccess

Add dev UC redirects (mirroring 11.1 for now)

Add dev UC redirects

---

netbeans.apache.org/src/content/download/nb111/nb111.asciidoc

After this one is approved, will do the same for the other Download pages.

List deployment platforms on Download page

---

netbeans.apache.org/src/content/participate/index.asciidoc
netbeans.apache.org/src/content/participate/submit-pr.asciidoc

Trying to help contributor to get correct path beetween contribution and donation.

Code donation section

---

netbeans.apache.org/src/content/download/nb112/index.asciidoc

Made Performance and Gradle Enhancements more detailed.
Made the links look as actual links.

Nb112 enhancements

---

netbeans.apache.org/src/content/download/nb112/nb112.asciidoc

Use the word "KEYS" to link to the KEYS file.

[NETBEANS-3324] Use KEYS for the link to KEYS

---

netbeans.apache.org/src/content/dtds/EditorFontsColors-1_2.dtd

As of: https://github.com/apache/netbeans/pull/1661

[NETBEANS-3440] Adding the new EditorFontsColors 1.2 DTD

---

netbeans.apache.org/src/content/kb/docs/java/index.asciidoc

- add title for your tube linke
- update JavaFX tutorial links to point to latest Oracle stuff
- added link to openjfx and NetBeans doc

Update links for JavaFX

---

netbeans.apache.org/src/content/download/archive/index.asciidoc
netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/download/nb112/nb112.asciidoc
netbeans.apache.org/src/content/templates/news.gsp

I think this is the move to make 11.3 public

Banner move to 11.3, 11.2 move in archive

---

netbeans.apache.org/globals.yml
netbeans.apache.org/src/content/templates/sitemap.gsp

Enable sitemap generation adding sitemap template

Generate sitemap

---

netbeans.apache.org/build.gradle
netbeans.apache.org/gradle/deps.gradle

Adding CSS sourcemaps for better debugging of SCSS in browsers.

CSS source maps

---

netbeans.apache.org/src/content/download/index.asciidoc

in the second half of the month

Next LTS is in May according to release schedule

---

netbeans.apache.org/src/content/tutorials/nbm-quick-start.asciidoc

There is an issue in the display of this piece of code on page https://netbeans.apache.org/tutorials/nbm-quick-start.html#_publishing_and_subscribing_to_the_lookup.

Fixed some typos in "Publish to the Lookup" part.

---

netbeans.apache.org/src/content/index.asciidoc
netbeans.apache.org/src/content/participate/report-issue.asciidoc

Make it easier for users to find how to submit a new issue.

filing issues

---

netbeans.apache.org/src/content/download/index.asciidoc

download page for 12.0

---

netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/download/nb121/nb121.asciidoc
netbeans.apache.org/src/content/templates/news.gsp

Update and link in pages for Apache NetBeans 12.1 release; fix various download links.

Update and link in pages for Apache NetBeans 12.1 release

---

netbeans.apache.org/build.gradle

Make build task to depends on buildSite task

Fix build task

---

netbeans.apache.org/src/content/download/dev/index.asciidoc

Modified the list of build instructions to be more readable and precise.

Update build instructions

---

netbeans.apache.org/src/content/kb/docs/contributing.asciidoc

Various spelling fixes and changes to wording.

Minor editorial cleanups

---

netbeans.apache.org/src/content/download/nb122/index.asciidoc

Added three features from PHP 8.0 support.
Restructured PHP 8.0 features.

Added missing PHP 8.0 features implemented

---

netbeans.apache.org/src/content/download/archive/index.asciidoc
netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/download/nb122/nb122.asciidoc
netbeans.apache.org/src/content/templates/news.gsp

I'm going to merge this. Tomorrow I'll have a busy day, so I won't be able to deal with NetBeans.

Apache NetBeans 12.2 Release

---

netbeans.apache.org/src/content/download/nb121/nb121.asciidoc

The review requests are for notification purpose only.

Moved Apache NetBeans 12.1 to the Archives

---

netbeans.apache.org/src/content/index.asciidoc

The link to "filing issues"  page led to a "NOT-FOUND" page.

Update the link to filing issues

---

netbeans.apache.org/src/content/.htaccess

Revised update for new VM domain cc/ @geertjanw

Update .htaccess for 12.3 release

---

netbeans.apache.org/src/content/participate/index.asciidoc

Added section how to validate reported issues.

Added Validating issues

---

netbeans.apache.org/src/content/download/index.asciidoc

Fixed "feature update 1" to "feature update 2".

Fixed NetBeans 12.2 title

---

netbeans.apache.org/src/content/.htaccess

INFRA-21530

---

netbeans.apache.org/src/content/.htaccess

Some additional redirections from the /features section.

some netbeans.org additional redirections

---

netbeans.apache.org/src/content/download/archive/index.asciidoc

Updating links to previous NetBeans versions.

[NETBEANS-5416] Oracle download links

---

netbeans.apache.org/src/content/.htaccess

Redirecting http://netbeans.org/downloads/ to /download/index.html

[NETBEANS-5420] Proper redirection of /downloads

---

netbeans.apache.org/src/content/participate/report-issue.asciidoc

https://issues.apache.org/jira/browse/NETBEANS-5338
Added emphasized link to JIRA.

[NETBEANS-5338] Added more prominent link to JIRA

---

netbeans.apache.org/src/content/.htaccess

https://issues.apache.org/jira/browse/NETBEANS-5338
Redirects to Reporting issues page instead of JIRA.

[NETBEANS-5338] Updated link to issue reporting

---

.asf.yaml

Create the minimal asf yaml to prepare site publish changes.

Add repo information and publish branch

---

Jenkinsfile.groovy

Make the build file modifiable through git instead of vi :D.
added groovy extension to be fine with Apache NetBeans.

website build file for CI

---

netbeans.apache.org/src/content/kb/docs/websvc/intro-ws.asciidoc

Updated and restructured web service introduction.
Kept links to knowledge tutorials on specific parts (even if these have not been reviewed yet).

Review of knowledge base web service introduction

---

netbeans.apache.org/src/content/kb/docs/index.asciidoc

___NetBeans Tutorials___
https://netbeans.apache.org/kb/docs/
👉 Nasty additional, unnecessary __amp;__ on docs index page is hurting my eyeballs! 👁️ 👀 😄

remove additional 'amp;'

---

netbeans.apache.org/src/content/jackpot/HintsFileFormat.asciidoc

added examples for imports and custom conditions. Mostly taken from the old bitbucket wiki, minor updates.

[jackpot wiki] imports and custom conditions

---

netbeans.apache.org/src/content/wiki/DevFaqChangeLookAndFeel.asciidoc

* Replaced HTML tags with asciidoc format
* Fixed broken link

Fixed broken link and asciidoc errors

---

netbeans.apache.org/src/content/tutorials/nbm-nodesapi2.asciidoc

Fixed styling of SGML entities
Fixed broken image URL

Fixed styling and broken link

---

netbeans.apache.org/src/content/tutorials/nbm-selection-1.asciidoc
netbeans.apache.org/src/content/tutorials/nbm-selection-2.asciidoc

Fixed various broken image links in selection tutorial part 1 and 2

Fixed various broken image links

---

netbeans.apache.org/src/content/tutorials/nbm-projecttype.asciidoc

Reviewing the project type tutorial.

Project type tutorial review

---

netbeans.apache.org/src/content/wiki/UsingFileSystemsMasterfs.asciidoc

Recovering documentation from https://web.archive.org/web/20100128225449/http://wiki.netbeans.org/UsingFileSystemsMasterfs

Recovering UsingFileSystemsMasterfs

---

netbeans.apache.org/src/content/tutorials/nbm-projectextension.asciidoc

Minor fixes in source code blocks (subs="macros")

Reviewing nbm-projectextension.asciidoc

---

netbeans.apache.org/src/content/kb/docs/web/ajax-quickstart.asciidoc

Minor changes, link to web archive source

Review of ajax-quickstart.asciidoc

---

netbeans.apache.org/src/content/tutorials/nbm-code-completion.asciidoc

Minor asciidoc stuff, removed link to previous versions.

Review of nbm-code-completion

---

netbeans.apache.org/src/content/download/nb13/index.asciidoc

This is just a raw edited generated list form GutHub. Sharing it so we everyone can contribute refining this.

Generared NB13 index page from GitHub PR-s

---

netbeans.apache.org/src/content/.htaccess

Update .htaccess for NetBeans 14. (plugins set to NB13 temporarily)

Update .htaccess for NetBeans 14

---

netbeans.apache.org/build.gradle
netbeans.apache.org/src/content/doap_NetBeans.rdf

this is a first try do have a doap file for Apache NetBeans to have bit more information populated here:
https://projects.apache.org/project.html?netbeans content may be adjusted later if some point are missing

add doap for Apache NetBeans

---

netbeans.apache.org/src/content/participate/codeconventions.asciidoc
netbeans.apache.org/src/content/participate/submit-pr.asciidoc

code convention was a dead link asciidoc made using
https://web.archive.org/web/20121018174418/http://netbeans.org/community/guidelines/code-conventions.html

missing convention files from submit-pr

---

netbeans.apache.org/src/content/participate/qualityevangelism.asciidoc

add the missing former quality evangelism page milestone section removed but still needs review.

add quality evangelism page

---

netbeans.apache.org/src/content/participate/report-issue.asciidoc

small updates:
- increase probability that someone is reading the notes by moving the link down
- emphasize "latest NetBeans" a little bit by linking to the download page since the user might not know what current is

Update report-issue page

---

netbeans.apache.org/src/content/download/archive/index.asciidoc
netbeans.apache.org/src/content/download/index.asciidoc
netbeans.apache.org/src/content/download/nb14/index.asciidoc
netbeans.apache.org/src/content/download/nb15/index.asciidoc
netbeans.apache.org/src/content/templates/news.gsp

uses of constants to ease for next release.

download pages for netbeans 15

---

netbeans.apache.org/src/content/blogs/geertjan/index.adoc
netbeans.apache.org/src/content/inc/database.adoc
netbeans.apache.org/src/content/kb/docs/cnd.adoc
netbeans.apache.org/src/content/kb/docs/cnd/HowTos.adoc
netbeans.apache.org/src/content/kb/docs/cnd/beginning-jni-linux.adoc
netbeans.apache.org/src/content/kb/docs/cnd/c-unit-test.adoc
netbeans.apache.org/src/content/kb/docs/cnd/cpp-vcs.adoc
netbeans.apache.org/src/content/kb/docs/cnd/debugging.adoc
netbeans.apache.org/src/content/kb/docs/cnd/depchecking.adoc
netbeans.apache.org/src/content/kb/docs/cnd/development-environment.adoc
netbeans.apache.org/src/content/kb/docs/cnd/navigating-editing.adoc
netbeans.apache.org/src/content/kb/docs/cnd/quickstart.adoc
netbeans.apache.org/src/content/kb/docs/cnd/remote-modes.adoc
netbeans.apache.org/src/content/kb/docs/cnd/remotedev-tutorial.adoc
netbeans.apache.org/src/content/kb/docs/cnd/toolchain.adoc
netbeans.apache.org/src/content/kb/index.adoc

some fixes and regrouping for c++

---

netbeans.apache.org/src/content/kb/docs/java/quickstart-gui.adoc

replaced wrong link with right one to the section "Previewing your GUI"

Update quickstart-gui.adoc: wrong link replaced with right one

---

netbeans.apache.org/src/content/kb/docs/java/code-inspect.adoc

library can be found there: https://web.archive.org/web/20131021173103/https://netbeans.org/project_downloads/samples/Samples/Java/library.zip

link to webarchive site

---

netbeans.apache.org/src/content/help/commercial-support.adoc

Add Codelerity Ltd. to list of commercial support options.

Add Codelerity to support options

---

netbeans.apache.org/src/content/download/nb16/index.adoc

Switch download page to archive links for Apache NetBeans 16.

Archive NetBeans 16.

---

netbeans.apache.org/src/content/.htaccess

Update .htaccess for NetBeans 18. Also update dev plugins which was missed earlier - need to keep in track with current release.

Update .htaccess for NetBeans 18

---

Jenkinsfile.groovy

Try checking last successful commit so that build can be restarted in case of abort or error.

Update Jenkinsfile.groovy to check last successful commit

---

netbeans.apache.org/globals.yml
netbeans.apache.org/src/content/templates/templatesparts/wiki-devbread.gsp
netbeans.apache.org/src/content/templates/templatesparts/wiki-devindexbread.gsp
netbeans.apache.org/src/content/templates/wikidev.gsp
netbeans.apache.org/src/content/templates/wikidevindex.gsp
netbeans.apache.org/src/content/wiki/DevFaqActionAddAnyFolder.adoc
netbeans.apache.org/src/content/wiki/DevFaqActionAddDataObject.adoc
netbeans.apache.org/src/content/wiki/DevFaqActionAddJavaPackage.adoc
netbeans.apache.org/src/content/wiki/DevFaqAppLifecycleHooks.adoc
netbeans.apache.org/src/content/wiki/DevFaqIndex.adoc

This is a bit of rework for wiki dev index (very incomplete) to have more the idea of writing only the Dev* file and let template do the index.
wiki entry page should be reworked a bit to be one header level less.
section label are a bit long to be backward compatible.
http://localhost:8080/wiki/DevFaqIndex.html

More wiki template 

---

netbeans.apache.org/src/content/ns/nb-module-project/3.xsd

find the xsd via waybackmachine.
Maybe we should check the redirect once published.
I thinks it's ok to re license as it was part of donation.

add nb module project v3

---

netbeans.apache.org/globals.yml
netbeans.apache.org/src/content/blogs/annnb17.adoc
netbeans.apache.org/src/content/blogs/annnb18.adoc
netbeans.apache.org/src/content/blogs/index.adoc
netbeans.apache.org/src/content/templates/blogentry.gsp
netbeans.apache.org/src/content/templates/blogindex.gsp
netbeans.apache.org/src/content/templates/feed.ftl
netbeans.apache.org/src/content/templates/templatesparts/menu.gsp

I this is a PR to backup blogs
tag: should be post to be part of the RSS
Need adjustment to have nice looking page.
blogs/index.html will contains generated index file from the post.
feed.xml will contains RSS
blogs/annnb17.adoc  should contains date, title and the following entry to be considered as post
:jbake-type: post
:jbake-tags: blogentry

Adding a blog + RSS

---

netbeans.apache.org/src/content/scss/common/_netbeans.scss
netbeans.apache.org/src/content/templates/blogentry.gsp
netbeans.apache.org/src/content/templates/blogindex.gsp

Hi,
just a bit of polish to get former looking feeling. Date more readable, shrink a bit body in index.

bit more human looking page for blog

---

netbeans.apache.org/src/content/blogs/announce-apache-netbeans-12-3.adoc
netbeans.apache.org/src/content/blogs/announce-apache-netbeans-12-4.adoc
netbeans.apache.org/src/content/blogs/announce-apache-netbeans-12-5.adoc
netbeans.apache.org/src/content/blogs/announce-apache-netbeans-12-6.adoc
netbeans.apache.org/src/content/blogs/announce-apache-netbeans-13-released.adoc
netbeans.apache.org/src/content/blogs/announce-apache-netbeans-14-released.adoc
netbeans.apache.org/src/content/blogs/announce-apache-netbeans-15-released.adoc
netbeans.apache.org/src/content/blogs/announce-apache-netbeans-16-released.adoc
netbeans.apache.org/src/content/blogs/announce-apache-netbeans-18-released.adoc
netbeans.apache.org/src/content/blogs/better-news-correct-deprecation-of.adoc
netbeans.apache.org/src/content/blogs/jep-411-deprecate-the-security.adoc
netbeans.apache.org/src/content/blogs/jep-411-deprecate-the-security1.adoc
netbeans.apache.org/src/content/blogs/log4j-and-apache-netbeans.adoc
netbeans.apache.org/src/content/blogs/towards-fair-trade-for-foss.adoc

New for 2021, using the :author: and :revdate: as mentioned by @vieiro.
Seems to works.

more blog entry for 2021

---

netbeans.apache.org/src/content/kb/docs/contributing.adoc

Looks like menu and btn are supported too. Just want to show sample to user

adding menu button sample

---

netbeans.apache.org/src/content/kb/docs/java/code-inspect.adoc

Try to fix the table of code-inspect.adoc

---

netbeans.apache.org/src/content/download/index.adoc
netbeans.apache.org/src/content/download/nb19/index.adoc
netbeans.apache.org/src/content/templates/templatesparts/news.gsp

Update news banner to NetBeans 19 add new nb19 pages + archive 18
I thinks it's all that has to be done on website side.

Release NetBeans 19
